### ISSUE TITLE
Float

### ISSUE THREAD

**Issue by liliang-cn** [liliang-cn/learning#40]

**Comment by liliang-cn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [布局](https://trello.com/c/Vom1MCAZ/5-%E5%B8%83%E5%B1%80)

**Comment by liliang-cn** [comment]
# Tips

- 浮动容器高度坍塌，floated elements do not add height to their parent elements

**Comment by liliang-cn** [comment]
CSS伪元素::after用来创建一个伪元素，作为已选中元素的最后一个子元素。通常会配合content属性来为该元素添加装饰内容。这个虚拟元素默认是行内元素。
```css
.clearfix::after {
  display: block;
  content: "";
  clear: both;
}
```
