### ISSUE TITLE
Box Model

### ISSUE THREAD

**Issue by liliang-cn** [liliang-cn/learning#46]

**Comment by liliang-cn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [盒模型](https://trello.com/c/GN2UJTnX/1-%E7%9B%92%E6%A8%A1%E5%9E%8B)

**Comment by liliang-cn** [comment]
## 默认行为
box model默认的行为： 当设置元素`width`或者`height`时，指定的是内容的宽或者高，并不包含加在元素上面的padding、border以及margin
![box-model-default](https://user-images.githubusercontent.com/20553741/50469252-91843700-09e6-11e9-9c78-49ea13bf2c17.png)

**Comment by liliang-cn** [comment]
## 避免使用

- 神奇数字，如本该是30%，由于默认行为不包含padding等在内，可能设置26%会生效，但是这种方法不可靠
- 使用calc，计算宽度，可以实现目标，但是需要计算

**Comment by liliang-cn** [comment]
将`box-sizing` 的值设置为`border-box`， width和height设置的值都是包含了内容、padding和border的值。
![box-zising-border-box](https://user-images.githubusercontent.com/20553741/50469637-48cd7d80-09e8-11e9-952a-31d83d5ef02a.png)

**Comment by liliang-cn** [comment]
## 设置可预测box-sizing
```css
    :root {
      box-sizing: border-box;
    }

    *,
    ::before,
    ::after {
      box-sizing: inherit;
    }
```

需要兼容第三方css文件，则在所在元素的父元素添加：
`box-sizing: content-box;`

**Comment by liliang-cn** [comment]
Inline elements:

- respect left & right margins and padding, but not top & bottom
- cannot have a width and height set
- allow other elements to sit to their left and right.

Block elements:

- respect all of those
- force a line break after the block element
- acquires full-width if width not defined

Inline-block elements:

- allow other elements to sit to their left and right
- respect top & bottom margins and padding
- respect height and width

**Comment by liliang-cn** [comment]
## input样式

input的即使声明为block，宽度设置还是需要指定，未指定的将由size属性决定为一个默认值
```css
.login-form input:not([type=checkbox]):not([type=radio]) {
  display: block;
  width: 100%;
  margin-top: .2em;
}
```
